from datetime import datetime
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator
from typing import List


class FileType(str, Enum):
    CV = "CV"
    JD = "JD"
    
    
class MatchingBaseModel(BaseModel):
    # add created_at and updated_at fields autogenerated with current datetime at the moment of creation
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)
    
    # model_config = ConfigDict(
    #     validate_assignment=True,
    # )
    
    @model_validator(mode='after')
    @classmethod
    def update_updated_at(cls, values):
        values.updated_at = datetime.now()
        return values
    
    
class MatchingRequestBase(MatchingBaseModel):
    file_id: UUID = Field(default_factory=uuid4)
    filename: str
    type: FileType
    user_id: str
    url: str
    
class MatchingRequestMessage(MatchingRequestBase):
    pass

class MatchingRequestModel(MatchingBaseModel):
    file_id: UUID
    filename: str
    type: FileType
    user_id: str
    url: str
    text: str


class FileModel(MatchingBaseModel):
    id: UUID = Field(default_factory=uuid4)
    filename: str
    type: FileType
    user_id: str
    url: str
    text: str
    
class JD_Requirements(MatchingBaseModel):
    id: UUID = Field(default_factory=uuid4)
    skills: List[str]
    experience: List[str]
    education: List[str]
    
    
class Candidate_Capabilities(MatchingBaseModel):
    id: UUID = Field(default_factory=uuid4)
    skills: List[str]
    experience: List[str]
    education: List[str]
    
    
class CV_Match(MatchingBaseModel):
    id: UUID = Field(default_factory=uuid4)
    skills_match: List[str]
    experience_match: List[str]
    education_match: List[str]
    gaps: List[str]
    
    
class MatchingResultModel(MatchingBaseModel):
    id: UUID = Field(default_factory=uuid4)
    user_id: str
    cv: FileModel
    jd: FileModel
    jd_requirements: JD_Requirements
    candidate_capabilities: Candidate_Capabilities
    cv_match: CV_Match
    overall_match_percentage: float
    
    # function to create model from json by creating nested models first
    @classmethod
    def from_json(cls, json_data):
        cv = FileModel(**json_data['cv'])
        jd = FileModel(**json_data['jd'])
        
        # Handle both camelCase and snake_case field names for compatibility
        if 'JD_Requirements' in json_data:
            jd_requirements = JD_Requirements(**json_data['JD_Requirements'])
        elif 'jd_requirements' in json_data:
            jd_requirements = JD_Requirements(**json_data['jd_requirements'])
        else:
            raise ValueError("Missing JD requirements in the response")
            
        if 'Candidate_Capabilities' in json_data:
            candidate_capabilities = Candidate_Capabilities(**json_data['Candidate_Capabilities'])
        elif 'candidate_capabilities' in json_data:
            candidate_capabilities = Candidate_Capabilities(**json_data['candidate_capabilities'])
        else:
            raise ValueError("Missing candidate capabilities in the response")
            
        if 'CV_Match' in json_data:
            cv_match = CV_Match(**json_data['CV_Match'])
        elif 'cv_match' in json_data:
            cv_match = CV_Match(**json_data['cv_match'])
        else:
            raise ValueError("Missing CV match in the response")
            
        # Remove the keys we've already processed to avoid duplicates
        for key in ['cv', 'jd', 'JD_Requirements', 'jd_requirements', 
                   'Candidate_Capabilities', 'candidate_capabilities',
                   'CV_Match', 'cv_match']:
            if key in json_data:
                json_data.pop(key, None)
                
        return cls(
            cv=cv, 
            jd=jd, 
            jd_requirements=jd_requirements, 
            candidate_capabilities=candidate_capabilities, 
            cv_match=cv_match, 
            **json_data
        )
